version: "3"
services: 
  mysql:
    image: mysql 
    restart: always
    environment:
      MYSQL_DATABASE: 'My_classes'
      MYSQL_USER: 'elearning_user'
      MYSQL_PASSWORD: '123'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
  elearning: 
    build: .
    image: elearning_flask 
    restart: always
    ports: 
      - "4200:4200" 
    environment: 
      - FLASK_ENV=development 
    volumes: 
      - .:/app 